{10}{}{Герой}
{20}{}{Героиня}
{30}{}{Житель Арройо}
{40}{}{Жительница Арройо}
{50}{}{Старешая/Хакунин}
{60}{}{Брамин}
{70}{}{Очень слабый муравей}
{80}{}{Слабый муравей}
{90}{}{Муравей}
{100}{}{Сильный муравей}
{110}{}{Мощный муравей}
{120}{}{Очень слабый скорпион}
{130}{}{Слабый скорпион}
{140}{}{Скорпион}
{150}{}{Сильный скорпион}
{160}{}{Мощный скорпион}
{170}{}{Очень слабая собака}
{180}{}{Слабая собака}
{190}{}{Собака}
{200}{}{Сильная собака}
{210}{}{Мощная собака}
{220}{}{Очень слабая крыса}
{230}{}{Слабая крыса}
{240}{}{Крыса}
{250}{}{Сильная крыса}
{260}{}{Мощная крыса}
{270}{}{Очень слабое растение}
{280}{}{Слабое хищное растение}
{290}{}{Хищное растение}
{300}{}{Сильное хищное растение}
{310}{}{Мощное хищное растение}
{320}{}{Очень слабый серебряный гекко}
{330}{}{Слабый серебряный гекко}
{340}{}{Серебряный гекко}
{350}{}{Сильный серебряный гекко}
{360}{}{Мощный серебряный гекко}
{370}{}{Очень слабый золотой гекко}
{380}{}{Слабый золотой гекко}
{390}{}{Золотой гекко}
{400}{}{Сильный золотой гекко}
{410}{}{Мощный золотой гекко}
{420}{}{Очень слабый крысокабан}
{430}{}{Слабый крысокабан}
{440}{}{Золотой крысокабан}
{450}{}{Сильный крысокабан}
{460}{}{Мощный крысокабан}