{10}{}{Герой}
{11}{}{ }
{20}{}{Героиня}
{21}{}{ }
{30}{}{Житель Арройо}
{40}{}{Жительница Арройо}
{50}{}{Человек в робе}
{60}{}{Брамин}
{61}{}{Двухголовая корова-мутант}
{70}{}{Очень слабый муравей}
{80}{}{Слабый муравей}
{90}{}{Муравей}
{100}{}{Сильный муравей}
{110}{}{Мощный муравей}
{120}{}{Очень слабый скорпион}
{130}{}{Слабый скорпион}
{140}{}{Скорпион}
{150}{}{Сильный скорпион}
{160}{}{Мощный скорпион}